### ISSUE TITLE
MacOS support would be great (and make sense)

### ISSUE THREAD

**Issue by davidvb** [ftischhauser/JPEGOptimizer#2]
Any plans for doing this? Would be greatly appreciated!

Cheers,
David

**Comment by ftischhauser** [comment]
It's on the radar, but unfortunately I couldn't find portable macOS binary builds of all the necessary tools and I don't have access to a mac to do that myself. The old 1.1 release supported macOS, but did not yet feature recompression.

If anyone wants to help out by providing custom macOS builds, I'd be happy to integrate them.

**Comment by LoriRow** [comment]
Hi There! A friend on Windows told me she loves the plugin. Unfortunately I have a Mac. I think my problem is I can't unzip the .zxp file. I can't open it to a lrplugin file which is what I think I need to use the Extension Manager. I'm on CS6. I downloaded both the file from Github and off Adobe as well. Both are .zxp - Thanks for your help! I'm looking forward to using the plugin. :)

**Comment by ftischhauser** [comment]
@LoriRow Glad to hear it's being used! Unfortunately the current version does not support MacOS at all until I can find a helping hand that provides the necessary tools.

However once support is enabled, the installation should be very similar as on Windows:
- Extract the ZIP (the should be no ZXP on GitHub) to any location you like. This ZIP contains one single folder called **JPEGOptimizer.lrplugin** with all scripts and tools in it.
- Use the Plugin Manager in Lightroom and choose this folder via the Add button.

You can already try that, but the plugin will only display the message "_Sorry, this version of JPEG Optimizer is not supported on macOS!_".

**Comment by gwinstanley** [comment]
So I've had a quick go at making a macOS version, which is just a naïve script which copies various files from Homebrew-installed packages. It seems to mostly work, but gives unexpected "Error exporting XMP data. (1)" when exporting using the 'Recompress JPEG' option with any residual metadata (i.e. it works when the 'Strip all metadata' option is checked), even though the various commands work ok when performed in the terminal.

Using the Homebrew versions should eventually provide support for macOS Sierra, which is hopefully sufficient. I've had a go at cross-compiling the utilities from source for 10.7 to give back-support to Lion and more recent, but **exiv2** is proving to be a real pain to recompile, mostly due to the XMP support provided by the Adobe XMP Toolkit, which refuses to compile successfully, and seems required by **exiv2** compilation. Anyhow when I eventually get the Homebrew sourced version up and running I'll post back again.

**Comment by ftischhauser** [comment]
@gwinstanley Awesome, thanks for looking into this!

The issue you saw is probably because Windows needs additional quotes for each `LrTasks.execute` call which breaks on macOS. So much for portable code. I have pushed a new branch called `macOS` that extends the workarounds over the new code, could you please test this version?

The plugin now expects the binaries to be in a separate `macOS` folder with the same structure and file names (minus '.exe') as the existing `WIN` folder.

I'd say if we can get macOS Sierra support only, that's still much better than nothing.

**Comment by ftischhauser** [comment]
Thanks to @gwinstanley's great work, macOS is now supported with release [v.2.0.2.1](https://github.com/ftischhauser/JPEGOptimizer/releases/tag/v2.0.2.1)! The update is currently pending approval from Adobe, but you can download the release directly from GitHub.

**Comment by LoriRow** [comment]
Thank you both! I'm not a programmer but I've heard from my Windows friends
how nicely this works to reduce files sizes for our website photos. Thanks
so much! :)


On Tue, Aug 1, 2017 at 5:06 AM, Flavio Tischhauser <notifications@github.com

**Comment by gwinstanley** [comment]
Unfortunately since upgrading my Homebrew copy of ImageMagick, the recompression has stopped working. After some investigation I find that the binaries for all except _jpeg-recompress_ have some hard-coded dynamic link to libraries within the Homebrew installations, but it only seems to be affecting the ImageMagick process for some reason. That means support for macOS is broken again until this can be resolved. I'll start looking into ways to create a statically-linked version of the various tools, but this isn't my area of expertise at all, so it may take some time.

**Comment by waxfingers** [comment]
I know nothing about coding, but I ❤️ this plug and saw that recently imagemagick updated their stuff, I figure it would not hurt to try and replace libraries and binaries at JPEGOptimizer.lrplugin/macOS. I think I managed most if not all of them; in imagemagick's folder had to rename a couple (the hard linked ones). Much for my surprise **seems to be working; I can export, recompress, strip exif and all that.**

osx 10.11.6
exiv2: stable 0.26
imagemagick stable 7.0.7-9
jpeg-archive: stable 2.1.1 
mozjpeg: stable 3.2

#BIG#
thank you @ftischhauser and @gwinstanley =)

**Comment by ftischhauser** [comment]
@waxfingers That's cool to hear! Do you know if your binaries are static builds and would work on a different Mac by simply copying those files? If so, it would be great if you could share your builds so others can test it.

**Comment by waxfingers** [comment]
Libraries are the ones that homebrew packet manager downloaded, compiled and linked to /usr/local/bin. Dunno if static, zero code knowledge, but if someone wants to try it, be my guess =)

https://drive.google.com/open?id=0Bxtrjp4jb-YsN2p4d0tkcjFseTg

**Comment by gwinstanley** [comment]
Unfortunately this is exactly what was happening in my case too, although I didn't realise at the time. The binaries were dynamically linked to libraries in the Homebrew installation, so once I upgraded the Homebrew versions, the links didn't work, as the binaries were trying to find the old versions. I've had a brief look since then, and seems it'll require at least statically-linked versions of ```mozjpeg``` and ```exiv2``` to retain the full functionality. _ImageMagick_ seems a major headache to statically link, but that tool is conveniently replaceable on macOS using a built-in tool called ```sips```. I've already done proof of concept tests on replacement of ```magick``` with ```sips```, but now need to find a way to correctly do the static compilation/linking of the other tools.

**Comment by waxfingers** [comment]
Meanwhile all the good people study and work on amelliorating stuff =) brew updates on imagemagick broke the plugin again. Case anypone's interested here's an ugly patched version that works (at least for me 10.11.6  ).

https://drive.google.com/open?id=1ytb_YF8FXWRN-LlhqKga--VWkU4Lgk_U

**Comment by ftischhauser** [comment]
Thanks to @gwinstanley the macOS support should now be fixed in [v2.0.3.3](https://github.com/ftischhauser/JPEGOptimizer/releases/v2.0.3.3).
