### ISSUE TITLE
Export doesn't work on Ligthroom Classic 7.3

### ISSUE THREAD

**Issue by camilledelbos** [ftischhauser/JPEGOptimizer#6]
Hi,
I'm comparing several jpeg tool (jpegmini, Jpegrescan plugin, etc.) and came across JPEGOptimizer. But couldn't use it because when I launch the export the lightroom window appears saying "Some export couldn't be done - Error exporting XMP data"
I'm translating from French but I guess you know which window I'm talking about.
Thanks for your help.
CD

**Comment by ftischhauser** [comment]
Hi,
Sorry for not noticing this issue earlier. What version of the plugin are you using? Are you running MacOS or Windows?

**Comment by townsesj** [comment]
Hi there,
I am experiencing the same error message as Camilledelbos

Running the export with JPEGOptimizer enabled as a post processing function, the export (LR’s) works but then I get a pop up error message stating 

_Some export operations were not performed_

_error exporting XMP data. (1)
 - DSCF1234.RAF_

I re-installed the plugin, same error.
Also I tried export with .RAF(Fuji) and .CR2 files, just to check it wasn’t a specific file type error. It wasn't :) 

My system info is copied below if this helps in any way? Happy to assist testing this.
I will also install the plugin on a Windows machine and see if the error replicates itself on that. 

System Info..

Lightroom Classic version: 7.4 [ 1176617 ]
License: Creative Cloud
Language setting: en
Operating system: Mac OS 10 High Sierra
Version: 10.13.5 [17F77]
Application architecture: x64
Logical processor count: 8
Processor speed: 2.5 GHz
Built-in memory: 16,384.0 MB
Real memory available to Lightroom: 16,384.0 MB
Real memory used by Lightroom: 4,535.1 MB (27.6%)
Virtual memory used by Lightroom: 9,337.8 MB
Memory cache size: 262.1MB
Internal Camera Raw revision: 976
Maximum thread count used by Camera Raw: 5
Camera Raw SIMD optimization: SSE2,AVX,AVX2
Camera Raw virtual memory: 2197MB / 8191MB (26%)
Camera Raw real memory: 2226MB / 16384MB (13%)
Displays: 1) 3840x2160

Graphics Processor Info: 
Metal: AMD Radeon R9 M370X



Application folder: /Applications/Adobe Lightroom Classic CC
Library Path: /Users/Simon/Pictures/Lightroom/*******.lrcat
Settings Folder: /Users/Simon/Library/Application Support/Adobe/Lightroom

Installed Plugins: 
1) AdobeStock
2) Aperture/iPhoto Importer Plug-in
3) Canon Tether Plugin
4) ColorChecker Passport
5) Facebook
6) Flickr
7) GooglePhoto
8) HDR Efex Pro 2
9) irista
10) jf Creative Commons
11) jf Geocoding Support
12) jf Metadata Wrangler
13) jf Snapshot on Export
14) John's big note
15) JPEG Optimizer
16) LR/Instagram
17) Macphun Creative Kit
18) Noiseless CK
19) SmugMug
20) Snapheal CK
21) Teekesselchen

Cheers

Simon

I should add that I tried all four compression methods. All returned the same error.

**Comment by ftischhauser** [comment]
Thanks! This might be a macOS specific bug, thankfully @gwinstanley has helped out again and recently provided a couple of fixes. Could you please try [v2.0.3.1](https://github.com/ftischhauser/JPEGOptimizer/releases/download/v2.0.3.1/JPEGOptimizer-2.0.3.1.zip)?

**Comment by townsesj** [comment]
Hi, tried version 2.0.3.1 
I have a new error message now..

_The export post-processing filter failed to render the file. (1)

DSCF1234.CR2_

Sorry! :)

**Comment by townsesj** [comment]
I also did some limited testing with Win10 / LR / JpegOptimizer 2.0.3.1 as well (which works fine!) 
From a sample file I obtained the following compression sizes (original and LR jpeg export sizes shown for comparison) 
Original .cr2 file - 33752kb
LR 100% quality .jpg  - 14587Kb
Jpeg Optimizer (no recompression) - 13931KB
Jpeg Optimizer (recompression/SmallFry/Very High) - 5124KB
Jpeg Optimizer (recompression/SSIM/Very High) - 2694KB
Jpeg Optimizer (recompression/SmallFry/Medium) - 1258KB

I have yet to fully review the quality quality of each of them but the results look very promising.
I guess each will have their own use dependant on what I need the files for.

This may not be helpful for bug fixing but maybe to anyone looking to use JPEG Optimizer

**Comment by gwinstanley** [comment]
I'm assuming this issue arises on macOS, in which case my guess would be that it's the older version of ImageMagick unable to read/process the raw file for some reason. Do you have a test CR2 file from the same camera which I could use to help diagnose the issue?

**Comment by townsesj** [comment]
Hi sorry for the delay in replying but yes I can provide a file no problem.

I would say however that its not just .cr2 files (Canon 5D MkIV) that are not processing, the same issue arises with .raf flies (Fuji X-100S) and older .crw (Canon 60D) so I don't believe its a file problem. 

Why? Mainly because I have been able to get it to work by stripping all the metadata using the option to do so available in the plugin itself. I was doing some research and came across the following article http://dev.exiv2.org/issues/1221 - Specifically the paragraph that states...
_"The reason for the message is because there is too much Exif data to be stored in the JPEG. No JPEG can ever store more than 64k of Exif metadata because of the design of the JPEG container. All Exif data must reside within a single APP1 segment which is limited to 64k bytes."_

I should add that I am a photographer rather than a developer (but do have an IT background to draw on) so I am only trying different approaches rather than looking at code :) 

So the current state of play for me is that I can use JPEG Optimizer (on my Mac) by stripping all the metadata. I don't want to publish anything though without some basic/essential metadata (copyright/author etc) so will look at using a couple of Jeffrey Friedl's excellent plugins  (Metadata Wrangler & Creative Commons) 
I am hopeful that I can use his Metadata Wrangler plugin to 'streamline' the metadata on my images prior to JpegOptimizer processing them and that it will then work its magic without complaint!  
Or failing that, use the Creative Commons plugin in post process after Jpeg optimisation processing in order to write metadata that I deem essential to have, back onto the compressed jpeg.
I will let you know how I get on!
And sorry for the long comment but I hope the information is useful?
Cheers Simon

**Comment by townsesj** [comment]
CR2 and RAF test files are too large 33Mb native and 25Mb zipped! This site has a 10Mb limit :(
So links here to my Dropbox :)
https://www.dropbox.com/s/1kqkftutgtv6ei9/ORiGINAL%20%28CANON%29.CR2?dl=0 
https://www.dropbox.com/s/mq14ivtqpbykupp/ORiGINAL%28FUJI%29.RAF?dl=0

**Comment by gwinstanley** [comment]
Thanks for the files. Curiously it works on my setup, although I'm using LR 6.14 (as I don't have CC). From what you say about _exiv2_ trying to add too much metadata, this shouldn't be an issue with v2.0.3.1 as the errors are suppressed when reinserting metadata.

Given the message ("The export post-processing filter failed to render the file. (1)") it may instead be some issue arising when LR tries to render the TIFF ready for more processing. Since I'm unable to reproduce this issue, and if you're feeling so inclined, you could enable logging in the plugin and see how far it gets with processing to help diagnose at which point in the workflow the issue appears.

To enable logging, do this when LR is closed or plugin is disabled:
1. Locate the **JPEGOptimizer.plugin** folder in the Finder.
2. Option-click on it and select _Show Package Contents_
3. Open the file **JPEGOptimizer.lua** in a text editor.
4. Remove the two initial hyphens on line 44.
5. Save the file.

To view log output:
1. Open macOS **Console** application (in _/Applications/Utilities_).
2. Select **system.log** on left-hand side.
3. Enter `JPEGOptimizer` in the search/filter field at the top-right.
4. Log output should now appear here as it happens.

By seeing which (if any) log messages are produced, this can help determine the stage of processing at which any error occurred. To simply matters it likely helps to clear the log display between export attempts.

**Comment by townsesj** [comment]
Hi - sorry for the delay.
I could not find any logs under system log but... did find the following under Devices and User reports 
Also error message has gone back to 

_error exporting XMP data. (1)_

!?!

[Log from Console (Devices) No info found in System Log.txt](https://github.com/ftischhauser/JPEGOptimizer/files/2231292/Log.from.Console.Devices.No.info.found.in.System.Log.txt)
[error messages User reports.txt](https://github.com/ftischhauser/JPEGOptimizer/files/2231309/error.messages.User.reports.txt)
[Console Log (Devices) with remove Exif thumbnail only .txt](https://github.com/ftischhauser/JPEGOptimizer/files/2231319/Console.Log.Devices.with.remove.Exif.thumbnail.only.txt)

**Comment by gwinstanley** [comment]
Ok, I think I've found the issue. The **macOS-binaries** ZIP archive I uploaded contained a dynamic library for _exiv2_ (`libexiv2.26.0.0.dylib`) along with a symbolic link pointing to it (`libexiv2.26.dylib`). This symbolic link got corrupted between there and the distribution bundle, such that the `libexiv2.26.dylib` file is no longer a symlink. I failed to notice when I originally tested as the file was obviously found elsewhere on my system.

@ftischhauser The distribution bundle needs fixing to ensure the symlink is maintained. They seemed to survive ok for the first release with macOS support, so something must have changed with your distribution bundling strategy. Let me know when you get a chance to bundle again, and I can test it for you. If that doesn't work then it'll probably work by renaming file `libexiv2.26.0.0.dylib` to `libexiv2.26.dylib` (and not using a symlinked file at all). From what I can tell it's the latter which _exiv2_ is really looking for.

**Comment by townsesj** [comment]
@gwinstanley - I changed the file names (renamed the libexiv2.26.dylib file to .old & libexiv2.26.0.0.dylib to libexiv2.26.dylib - Definitley works for me - Exported perfectly with metadata intact. 👍 
I realise this was more aimed at Flavio @ftischhauser but I thought Id try it!
Thanks (to you both) and happy to help out whenever (like testing the bundle for instance when fixed)

**Comment by ftischhauser** [comment]
Oops, I did not notice that symlink. I have now prepared a new package that seems to unpack correctly on Linux, but I would appreciate if you could do a full LR test on macOS with this: [JPEGOptimizer-2.0.3.2.zip](https://github.com/ftischhauser/JPEGOptimizer/files/2238660/JPEGOptimizer-2.0.3.2.zip)

**Comment by gwinstanley** [comment]
The symlinks are correctly preserved this time, but the executables have incorrect permissions, and need all-user executable permission to function (i.e. `chmod a+x macOS/ImageMagick/convert` etc. for each binary).

**Comment by townsesj** [comment]
happy to try once exe's are correct (permission wise) :)

**Comment by ftischhauser** [comment]
Ah, that must be a side effect of switching the packaging over to Linux - Although it's surprising that a Windows ZIP adds +x by default. But let's see if this helps: 
[JPEGOptimizer-2.0.3.3.zip](https://github.com/ftischhauser/JPEGOptimizer/files/2248987/JPEGOptimizer-2.0.3.3.zip)

**Comment by gwinstanley** [comment]
Yes, this version works perfectly (on my installation of macOS) :)

**Comment by townsesj** [comment]
Seems to be working perfectly on mine too, like a charm in fact!  👍 :)
Thanks guys - much appreciated effort & support from you both.
It's a really useful addition to my LR workflow and believe me, it will be used extensively! 🥇  
BR 
Simon

**Comment by ftischhauser** [comment]
Awesome, thank you both for testing and especially @gwinstanley for your contributions!
