### ISSUE TITLE
JPEGOptimizer overrides Lightroom file limit setting

### ISSUE THREAD

**Issue by Pigprof** [ftischhauser/JPEGOptimizer#8]
Hi Guys,
I've just spent hours grappling with an issue.  Although I set the Lightroom 'Limit file size' to 200 kb on one of my presets the limit was not being honoured.  Indeed, in some cases, the file size was actually increasing.  e.g. an initial file ca. 800 kb exported with a 200 kb file limit set, returned a file size ca. 1800 kb.  Eventually, I discovered that JPEGOptimizer was active on that export preset and it turns out that it overrides the Limit file size selection.  So, I assume that the plugin should only be used when no limit is put on file size in the native Lightroom selections.  It would be good to add this as a warning.  I now have to go through a large web media file, remove and resize a whole load of images that I thought had been correctly resized.

BTW I am running the latest version of LrC so has something been changed that is creating a conflict with JPEGOptimizer.  I still can't see how JPEGOptimizer can increase file size.   
Thanks

Peter

**Comment by ftischhauser** [comment]
Hi Peter
Thanks for your report. The behavior you have observed is by design when using the "Recompress JPEG" option, as this will no longer use Lightroom for any JPEG compression steps (which includes settings such as the file size limit). I agree that this is probably not very obvious, so I have added a sentence to highlight this in the readme.
If you only use the "Lossless Optimizations", the plugin will work with the JPEG created by Lightroom, so the file size limit will still be effective. However, the resulting file is hopefully a bit smaller than the configured limit, since the processing happens after Lightroom created the file.

**Comment by Pigprof** [comment]
Thanks for the reply.  I guessed this was the case, it was just that I had not read it anywhere so the result was unexpected.  I’m glad you have highlighted it in the readme.

 

Thanks again

 

Peter
